spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          # for correct api gateway work
          enabled: true
          # ignores letters case
          lower-case-service-id: true

server:
  port: 8765