spring:
  application:
    name:
      todo-eureka-server

# for disabling registration of microservices to registry
eureka:
  client:
    # no need to register microservices from this module
    register-with-eureka: false
    fetch-registry: false

    # where we are going to register application
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

server:
  port: 8761