spring:
  application:
    name: todo-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ravshanbekn/todo-config.git
          clone-on-start: true
          basedir: file://c:/tmp/git-config
          username: ${GIT_USERNAME:}
          password: ${GIT_TOKEN:}
          default-label: main

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  port: 8888
