spring:
  application:
    name: user-service

  # for reading configurations
  config:
    import: configserver:http://localhost:8888

  # for mutual parent files: "application-micro"
  profiles:
    active: micro

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/todo_user_db
    username: postgres
    password: postgres
