spring:
  application:
    name: user-service

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo_user_db
    username: postgres
    password: postgres

management:
  endpoint:
    gateway:
      access: unrestricted

  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"

eureka:
  client:
    # where we need to register microservices
    service-url:
      defaultZone: http://localhost:8761/eureka/

  # every instance should have unique id
  instance:
    instance-id: ${spring.application.name}:${server.port}

api-gateway:
  host: localhost
  port: 8765

server:
  port: 8080