spring:
  application:
    name: task-service

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/todo_task_db
    username: postgres
    password: postgres

  cloud:
    function:
      definition: userCreatedEventConsumer
    stream:
      bindings:
        userCreatedEventConsumer-in-0:
          destination: user-created-topic
          content-type: application/json
    openfeign:
      circuitbreaker:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: rmuser
    password: rmpassword

eureka:
  client:
    # where we need to register microservices
    service-url:
      defaultZone: http://localhost:8761/eureka/

  # every instance should have unique id
  instance:
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoint:
    gateway:
      access: unrestricted

  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{yyyy-MM-dd HH:mm:ss} - %msg%n"

api-gateway:
  host: localhost
  port: 8765

server:
  port: 8090
  error:
    include-message: always
