version: "3.9"
services:
  user-service:
    image:
      postgres:13
    environment:
      POSTGRES_DB: "todo_user_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"